spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mintyn
    username: root
    password: rooting
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: mysql
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect